// svelte/src/lib/GreetingCard.svelte
<script>
import { onMount } from "svelte";

let userName = "Click to enter name";
let editMode = false;

onMount(() => {
	const storedName = localStorage.getItem("userName");
	if (storedName) userName = storedName;
});

const saveName = () => {
	localStorage.setItem("userName", userName);
	editMode = false;
};

function getGreeting() {
	const hour = new Date().getHours();
	if (hour < 12) return "Good morning";
	if (hour < 18) return "Good afternoon";
	return "Good evening";
}
</script>
  
  {#if editMode}
	<input
	  class="username-input"
	  bind:value={userName}
	  on:blur={saveName}
	  on:keyup="{(e) => e.key === 'Enter' && saveName()}"
	/>
  {:else}
	<button class="greeting" on:click={() => (editMode = true)} on:keydown="{(e) => e.key === 'Enter' && (editMode = true)}">
	  {getGreeting()}, <span class="username">{userName}</span> :)
	</button>
  {/if}
  
  <style>
	.greeting {
	  font-size: 2rem;
	  text-align: center;
	  cursor: pointer;
	  border: none;
	  background: none;
	  color: white;
	  font-weight: bold;
	  padding: 10px;
	}
  
	.username {
	  font-weight: bold;
	  color: lightblue;
	}
  
	.username-input {
	  font-size: 2rem;
	  text-align: center;
	  border: none;
	  background: none;
	  color: white;
	  width: 100%;
	  outline: none;
	}
  </style>

// vue/src/components/GreetingCard.vue
<template>
	<h2 @click="editMode = true" v-if="!editMode">{{ greetingMessage }}, <span class="username">{{ userName }}</span> :)</h2>
	<input
	  v-else
	  v-model="userName"
	  class="username-input"
	  type="text"
	  @blur="saveName"
	  @keyup.enter="saveName"
	/>
  </template>
  
  <script setup>
import { computed, onMounted, ref } from "vue";

const userName = ref(localStorage.getItem("userName") || "Click to enter name");
const editMode = ref(false);

const greetingMessage = computed(() => {
	const hour = new Date().getHours();
	if (hour < 12) return "Good morning";
	if (hour < 18) return "Good afternoon";
	return "Good evening";
});

const saveName = () => {
	localStorage.setItem("userName", userName.value);
	editMode.value = false;
};

onMounted(() => {
	userName.value = localStorage.getItem("userName") || "Click to enter name";
});
</script>
  
  <style scoped>
  h2 {
	font-size: 2rem;
	text-align: center;
	cursor: pointer;
  }
  
  .username {
	font-weight: bold;
	color: lightblue;
  }
  
  .username-input {
	font-size: 2rem;
	text-align: center;
	border: none;
	background: none;
	color: white;
	width: 100%;
	outline: none;
  }
  </style>
