// svelte/src/lib/ClockDisplay.svelte
<script>
import moment from "moment";
import { onMount } from "svelte";
let currentTime;

onMount(() => {
	setInterval(() => {
		currentTime = moment().format("HH:mm:ss");
	}, 1000);
});
</script>

<div class="clock">
	<h1>{currentTime}</h1>
</div>

<style>
	.clock {
		color: white;
		text-shadow: 1px 1px 4px rgba(0, 0, 0, 0.7);
		font-size: 2rem;
		text-align: center;
	}
</style>

// src/components/ClockDisplay.vue
<template>
    <div class="clock">
      <h1>{{ currentTime }}</h1>
    </div>
  </template>
  
  <script setup>
  import { ref, onMounted } from "vue";
  import moment from "moment";
  
  const currentTime = ref("");
  
  const updateTime = () => {
    currentTime.value = moment().format("HH:mm:ss");
  };
  
  onMounted(() => {
    updateTime();
    setInterval(updateTime, 1000);
  });
  </script>
  
  <style scoped>
  .clock {
    text-align: center;
  }
  
  .clock h1 {
    font-size: 5rem;
    margin: 0;
    color: white;
    text-shadow: 1px 1px 4px rgba(0, 0, 0, 0.7);
  }
  </style>
