// src/components/GreetingCard.vue
<template>
  <h2>{{ greetingMessage }}, {{ userName }} :)</h2>
</template>

<script setup>
import moment from "moment";
import { computed } from "vue";

const props = defineProps({
	userName: {
		type: String,
		required: true,
	},
});

const greetingMessage = computed(() => {
	const hour = moment().hour();
	if (hour < 12) return "Good morning";
	if (hour < 18) return "Good afternoon";
	return "Good evening";
});
</script>

<style scoped>
h2 {
  font-size: 2rem;
  margin-top: 10px;
  text-align: center;
}
</style>

// svelte/src/lib/GreetingCard.svelte
<script>
	export let userName;
	const hour = new Date().getHours();
	const greeting =
		hour < 12 ? "Good morning" : hour < 18 ? "Good afternoon" : "Good evening";
</script>

<h2 class="greeting">{greeting}, {userName} :)</h2>

<style>
	.greeting {
		color: white;
		text-align: center;
		font-size: 1.8rem;
	}
</style>
