// svelte/src/App.svelte
<script>
import BackgroundImage from "./lib/BackgroundImage.svelte";
import ClockDisplay from "./lib/ClockDisplay.svelte";
import DailyQuote from "./lib/DailyQuote.svelte";
import DateDisplay from "./lib/DateDisplay.svelte";
import GreetingCard from "./lib/GreetingCard.svelte";
import WeatherWidget from "./lib/WeatherWidget.svelte";

let userName = localStorage.getItem("username");
if (!userName) {
	userName = prompt("What is your name?");
	localStorage.setItem("username", userName);
}
</script>

<BackgroundImage>
	<DateDisplay />
	<WeatherWidget />

	<div class="overlay">
		<ClockDisplay />
		<GreetingCard {userName} />
		<DailyQuote />
	</div>
</BackgroundImage>

<style>
.overlay {
  position: absolute;
  inset: 0;
  background: rgba(0, 0, 0, 0.4);
  display: flex;
  justify-content: center;
  align-items: center;
  flex-direction: column;
}
</style>

// src/App.vue
<template>
  <BackgroundImage>
    <div class="overlay">
      <DateDisplay />
      <WeatherWidget />
      <div class="center-container">
        <ClockDisplay />
        <GreetingCard :user-name="userName" />
        <DailyQuote />
      </div>
    </div>
  </BackgroundImage>
</template>

<script setup>
import { onMounted, ref } from "vue";
import BackgroundImage from "./components/BackgroundImage.vue";
import ClockDisplay from "./components/ClockDisplay.vue";
import DailyQuote from "./components/DailyQuote.vue";
import DateDisplay from "./components/DateDisplay.vue";
import GreetingCard from "./components/GreetingCard.vue";
import WeatherWidget from "./components/WeatherWidget.vue";

const userName = ref("");

onMounted(() => {
	const storedName = localStorage.getItem("daily-app-user");
	if (storedName) {
		userName.value = storedName;
	} else {
		userName.value = prompt("What's your name?");
		localStorage.setItem("daily-app-user", userName.value);
	}
});
</script>

<style scoped>
.overlay {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background: rgba(0, 0, 0, 0.4);
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
}

.center-container {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 10px;
  color: white;
  text-shadow: 1px 1px 4px rgba(0, 0, 0, 0.7);
}
</style>
